/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.veia;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author noteB00k
 */
public class Veia_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Veia_Screen
     */
    public Veia_Screen() {
        initComponents();
        btn1.setVisible(false);
        btn2.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        btnFim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1.setText("Jogador1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("Jogador2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(0, 0, 0));

        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/veia/vazio.png"))); // NOI18N
        lbl2.setText("jLabel1");
        lbl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl2MouseClicked(evt);
            }
        });

        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/veia/vazio.png"))); // NOI18N
        lbl3.setText("jLabel1");
        lbl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl3MouseClicked(evt);
            }
        });

        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/veia/vazio.png"))); // NOI18N
        lbl1.setText("jLabel1");
        lbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl1MouseClicked(evt);
            }
        });

        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/veia/vazio.png"))); // NOI18N
        lbl4.setText("jLabel1");
        lbl4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl4MouseClicked(evt);
            }
        });

        lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/veia/vazio.png"))); // NOI18N
        lbl5.setText("jLabel1");
        lbl5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl5MouseClicked(evt);
            }
        });

        lbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/veia/vazio.png"))); // NOI18N
        lbl6.setText("jLabel1");
        lbl6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl6MouseClicked(evt);
            }
        });

        lbl7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/veia/vazio.png"))); // NOI18N
        lbl7.setText("jLabel1");
        lbl7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl7MouseClicked(evt);
            }
        });

        lbl8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/veia/vazio.png"))); // NOI18N
        lbl8.setText("jLabel1");
        lbl8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl8MouseClicked(evt);
            }
        });

        lbl9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/veia/vazio.png"))); // NOI18N
        lbl9.setText("jLabel1");
        lbl9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(panel1Layout.createSequentialGroup()
                    .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel1Layout.createSequentialGroup()
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnFim.setText("End");
        btnFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(174, 174, 174)
                        .addComponent(btnFim))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btn1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn2))))
                .addGap(0, 97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnFim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int jogador;
    boolean clicado1 = false;
    boolean clicado2 = false;
    boolean clicado3 = false;
    boolean clicado4 = false;
    boolean clicado5 = false;
    boolean clicado6 = false;
    boolean clicado7 = false;
    boolean clicado8 = false;
    boolean clicado9 = false;
    int pos1 ;
    int pos2 ;
    int pos3 ;
    int pos4 ;
    int pos5 ;
    int pos6 ;
    int pos7 ;
    int pos8 ;
    int pos9 ;
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        btn1.setVisible(true);
        btn2.setVisible(false);
        jogador =1;
    }//GEN-LAST:event_btnStartActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        btn1.setVisible(false);
        btn2.setVisible(true);
        jogador = 1;
        System.out.println("jogador"+jogador);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
         btn1.setVisible(true);
        btn2.setVisible(false);
        jogador = 2;
        System.out.println("jogador"+jogador);
    }//GEN-LAST:event_btn2ActionPerformed

    private void lbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl1MouseClicked
        if(clicado1 == false){
            if(jogador ==1){
            ImageIcon img = new ImageIcon(getClass().getResource("bola.png"));
            lbl1.setIcon(img);
            pos1 = 0;
        }else if(jogador ==2){
            ImageIcon img = new ImageIcon(getClass().getResource("xis.png"));
            lbl1.setIcon(img);
            pos1 = 2;
        }
        }
        clicado1 = true;
        System.out.println("nao pode clicar nesse");
        
    }//GEN-LAST:event_lbl1MouseClicked
    
    private void lbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl2MouseClicked
        if(clicado2 == false){
            if(jogador ==1){
            ImageIcon img = new ImageIcon(getClass().getResource("bola.png"));
            lbl2.setIcon(img);
            pos2 = 0;
        }else if(jogador ==2){
            ImageIcon img = new ImageIcon(getClass().getResource("xis.png"));
            lbl2.setIcon(img);
            pos2 = 2;
        }
        }
        clicado2 = true;
        System.out.println("nao pode clicar nesse");
    }//GEN-LAST:event_lbl2MouseClicked
   
    private void lbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl3MouseClicked
        if(clicado3 == false){
            if(jogador ==1){
            ImageIcon img = new ImageIcon(getClass().getResource("bola.png"));
            lbl3.setIcon(img);
            pos3 = 0;
        }else if(jogador ==2){
            ImageIcon img = new ImageIcon(getClass().getResource("xis.png"));
            lbl3.setIcon(img);
            pos3 = 2;
        }
        }
        clicado3 = true;
        System.out.println("nao pode clicar nesse");
    }//GEN-LAST:event_lbl3MouseClicked

    private void lbl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl4MouseClicked
        if(clicado4 == false){
            if(jogador ==1){
            ImageIcon img = new ImageIcon(getClass().getResource("bola.png"));
            lbl4.setIcon(img);
            pos4 = 0;
        }else if(jogador ==2){
            ImageIcon img = new ImageIcon(getClass().getResource("xis.png"));
            lbl4.setIcon(img);
            pos4 = 2;
        }
        }
        clicado4 = true;
        System.out.println("nao pode clicar nesse");
    }//GEN-LAST:event_lbl4MouseClicked

    private void lbl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl5MouseClicked
        if(clicado5 == false){
            if(jogador ==1){
            ImageIcon img = new ImageIcon(getClass().getResource("bola.png"));
            lbl5.setIcon(img);
            pos5 = 0;
        }else if(jogador ==2){
            ImageIcon img = new ImageIcon(getClass().getResource("xis.png"));
            lbl5.setIcon(img);
            pos5 = 2;
        }
        }
        clicado5 = true;
        System.out.println("nao pode clicar nesse");
    }//GEN-LAST:event_lbl5MouseClicked

    private void lbl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl6MouseClicked
        if(clicado6 == false){
            if(jogador ==1){
            ImageIcon img = new ImageIcon(getClass().getResource("bola.png"));
            lbl6.setIcon(img);
            pos6 = 0;
        }else if(jogador ==2){
            ImageIcon img = new ImageIcon(getClass().getResource("xis.png"));
            lbl6.setIcon(img);
            pos6 = 2;
        }
        }
        clicado6 = true;
        System.out.println("nao pode clicar nesse");
    }//GEN-LAST:event_lbl6MouseClicked

    private void lbl7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl7MouseClicked
        if(clicado7 == false){
            if(jogador ==1){
            ImageIcon img = new ImageIcon(getClass().getResource("bola.png"));
            lbl7.setIcon(img);
            pos7 = 0;
        }else if(jogador ==2){
            ImageIcon img = new ImageIcon(getClass().getResource("xis.png"));
            lbl7.setIcon(img);
            pos7 = 2;
        }
        }
        clicado7 = true;
        System.out.println("nao pode clicar nesse");
    }//GEN-LAST:event_lbl7MouseClicked

    private void lbl8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl8MouseClicked
        if(clicado8 == false){
            if(jogador ==1){
            ImageIcon img = new ImageIcon(getClass().getResource("bola.png"));
            lbl8.setIcon(img);
            pos8 = 0;
        }else if(jogador ==2){
            ImageIcon img = new ImageIcon(getClass().getResource("xis.png"));
            lbl8.setIcon(img);
            pos8 = 2;
        }
        }
        clicado8= true;
        System.out.println("nao pode clicar nesse");
    }//GEN-LAST:event_lbl8MouseClicked

    private void lbl9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl9MouseClicked
        if(clicado9 == false){
            if(jogador ==1){
            ImageIcon img = new ImageIcon(getClass().getResource("bola.png"));
            lbl9.setIcon(img);
            pos9 = 0;
        }else if(jogador ==2){
            ImageIcon img = new ImageIcon(getClass().getResource("xis.png"));
            lbl9.setIcon(img);
            pos9 = 2;
        }
        }
        clicado9 = true;
        System.out.println("nao pode clicar nesse");
    }//GEN-LAST:event_lbl9MouseClicked

    private void btnFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFimActionPerformed
        if(pos1 == pos2 && pos2 == pos3){
            if(jogador ==1){
            JOptionPane.showMessageDialog(null,"Jogador 1 venceu");
            }else if(jogador ==2){
            JOptionPane.showMessageDialog(null,"Jogador 2 venceu ");
            }
        }else if(pos1 == pos4 && pos4 == pos7){
            if(jogador ==1){
            JOptionPane.showMessageDialog(null,"Jogador 1 venceu");
            }else if(jogador ==2){
            JOptionPane.showMessageDialog(null,"Jogador 2 venceu ");
            }
        }else if(pos1 == pos5 && pos5 == pos9){
            if(jogador ==1){
            JOptionPane.showMessageDialog(null,"Jogador 1 venceu");
            }else if(jogador ==2){
            JOptionPane.showMessageDialog(null,"Jogador 2 venceu ");
            }
        }else if(pos4 == pos5 && pos5 == pos6){
           if(jogador ==1){
            JOptionPane.showMessageDialog(null,"Jogador 1 venceu");
            }else if(jogador ==2){
            JOptionPane.showMessageDialog(null,"Jogador 2 venceu ");
            }
        }else if(pos7 == pos8 && pos8 == pos9){
           if(jogador ==1){
            JOptionPane.showMessageDialog(null,"Jogador 1 venceu");
            }else if(jogador ==2){
            JOptionPane.showMessageDialog(null,"Jogador 2 venceu ");
            }
        }else if(pos2 == pos5 && pos5 == pos8){
            if(jogador ==1){
            JOptionPane.showMessageDialog(null,"Jogador 1 venceu");
            }else if(jogador ==2){
            JOptionPane.showMessageDialog(null,"Jogador 2 venceu ");
            }
        }else if(pos3 == pos6 && pos6 == pos9){
            if(jogador ==1){
            JOptionPane.showMessageDialog(null,"Jogador 1 venceu");
            }else if(jogador ==2){
            JOptionPane.showMessageDialog(null,"Jogador 2 venceu ");
            }
        }else if(pos7 == pos5 && pos5 == pos3){
            if(jogador ==1){
            JOptionPane.showMessageDialog(null,"Jogador 1 venceu");
            }else if(jogador ==2){
            JOptionPane.showMessageDialog(null,"Jogador 2 venceu ");
            }
        }else{
                JOptionPane.showMessageDialog(null, "Empate");
            }
    }//GEN-LAST:event_btnFimActionPerformed
  
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Veia_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Veia_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Veia_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Veia_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Veia_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btnFim;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
